// vue/vue-test/src/components/TestComponent.vue
<script setup lang="ts">
import { ref, reactive } from "vue";
import NavTd from "./common/Nav/Nav-td.vue";
import type { Path } from "./common/Nav/types";

const testPath = reactive<Path[]>([
  {
    path: "/",
    label: "test01",
    child: [
      {
        path: "/a",
        label: "test01子路由",
        child: null,
      },
      {
        path: "/b",
        label: "test02子路由",
        child: null,
      },
    ],
  },
  {
    path: "a",
    label: "test02",
    child: [
      {
        path: "a/c",
        label: "test02子路由",
        child: null,
      },
      {
        path: "a/d",
        label: "test02子路由2",
        child: null,
      },
    ],
  },
]);
</script>

<template>
  <div class="w-80 mx-auto">
    <NavTd :pathList="testPath"></NavTd>
  </div>
</template>

<style scoped></style>

// React/react-test/src/component/TestComponent.tsx
import { useState } from 'react'
import { NavTd } from './Nav/NavTd'
import type { Path } from './Nav/types'

export default function TestComponent() {
  const [pathList] = useState<Path[]>([
    {
      label: 'test01',
      path: 'test01Path',
      child: null,
    },
    {
      label: 'test02',
      path: 'test02Path',
      child: [
        {
          path: 'subPath1',
          label: 'sub1',
          child: null,
        },
      ],
    },
  ])
  return (
    <>
    <div className=" w-96 mx-auto font-bold">
      test TestComponent
    </div>
    <NavTd pathList={pathList}></NavTd>
    </>
  )
}
